### ISSUE TITLE
Specification should forbid the null character.

### ISSUE THREAD

**Issue by mikerobi** [defiant00/tyon#1]
Allowing the null character in a string is a really bad idea.

Correctly supporting this in languages with NULL terminated strings it requires a much more complicated parsing APIs.  
Even supporting an escaped NULL character would be an extreme headache.

Non NULL terminated languages are likely to have problems too as they often interface with C apis.

Forbidding it in strings is a must, but I can't think of any reason to allow it anywhere in the document.

**Comment by defiant00** [comment]
Thanks for the feedback, that's an excellent point. I've updated the spec to indicate that NULLs are not allowed in a valid TYON file.
